apiVersion: v1
kind: Service
metadata:
  name: codechops-wp
  labels:
    app: codechops-wp
  namespace: codechops
spec:
  selector:
    app: codechops-wp
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: codechops-wp
  namespace: codechops
  labels:
    app: codechops-wp
spec:
  serviceName: codechops-wp
  selector:
    matchLabels:
      app: codechops-wp
  replicas: 1
  template:
    metadata:
      labels:
        app: codechops-wp
    spec:
      containers:
      - image: mvpstudio/codechops-wordpress:v003
        name: wordpress
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
        env:
        - name: WORDPRESS_DB_HOST
          value: codechops-mdb.codechops:3306
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mdbsecrets
                key: user-password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: wp-data
            mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: wp-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
